---
title: "Bighorn data processing"
author: "Megan Sears"
date: "2022-06-17"
output:
  html_document:
    toc: true
    toc_float: true
    theme: journal
editor_options: 
  chunk_output_type: console
---

```{r open packages, include=FALSE}
library(tidyverse)
library(dplyr)
library(lubridate)
library(plotly)
library(ggplot2)
library(here)
library(scales)
```

## Loading in the data

```{r load in data}
# read in met data
met <- read_csv(here('raw_data', 'bighorn_met_composite.csv')) %>%
  mutate(dt_use = parse_date_time(datetime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%Y-%m-%d %H:%M'))) %>%
  select(-datetime) %>%
  mutate(Ta2_C = (Ta_F - 32) * 5/9) %>%
  mutate(Ta_C_use = coalesce(Ta_C, Ta2_C))

# read in tipping bucket data
rain <- read_csv(here('raw_data', 'bighorn_rain_composite_new.csv')) %>%
  mutate(dt_use = parse_date_time(datetime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%Y-%m-%d %H:%M'))) %>%
  select(-datetime) %>%
  mutate(precip_mm = tips * 0.1)

# read in stage data
stage <- read_csv(here('raw_data', 'bighorn_stage_composite_new.csv')) %>%
  mutate(dt_use = parse_date_time(DateTime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%m/%d/%Y %H:%M:%S',
                                             '%m/%d/%y %I:%M:%S %p'))) %>%
  select(-c(DateTime, T_C)) %>%
  rename(Pw_kPa = P_kPa)

# read in baro data
baro <- read_csv(here('raw_data' ,'bighorn_baro_composite_new.csv')) %>%
  mutate(dt_use = parse_date_time(datetime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%m/%d/%y %I:%M:%S %p',
                                             '%m/%d/%Y %H:%M:%S'))) %>%
  select(-c(datetime, T_C)) %>%
  rename(Pa_kPa = P_kPa)

#join stage and baro DFs to get stage height
stage <- left_join(stage, baro, by="dt_use")

# get stage in kPa, convert to stage in cm
stage <- stage %>%
  mutate(stage_kPa = Pw_kPa -Pa_kPa,
         stage_cm = stage_kPa * 10.197162129779)

write.csv(met, here('outputs', 'bighorn_met.csv'))
write.csv(rain, here('outputs', 'bighorn_rain.csv'))
write.csv(stage, here('outputs', 'bighorn_stage.csv'))

```

## Time series of each variable

```{r look at variables}
snowdepth <- ggplot(met, aes(x= dt_use, y = SnowD_m)) + 
  geom_line() +
  ggtitle('snow depth (m)') +
  scale_x_datetime(labels = date_format("%b-%Y")) +
  theme_bw()

ggplotly(snowdepth)
snowdepth

#estimate - after Mar 20, 2022 no snow
#estimate - after May 15, 2022 no snow

netrad_old <- ggplot(met %>%
                       drop_na(Rn_Wm2),
                     aes(x= dt_use, y = Rn_Wm2)) + 
  geom_point() +
  ggtitle('net rad_old (Wm2)') +
  scale_x_datetime(labels = date_format("%b-%Y")) +
  theme_bw()

#ggplotly(netrad_old)
netrad_old

windspeed <- ggplot(met, aes(x= dt_use, y = u_ms)) + 
  geom_point() +
  ggtitle('wind speed (m/s)') +
  scale_x_datetime(labels = date_format("%b-%Y")) +
  theme_bw()
 
#ggplotly(windspeed)
windspeed

sm <- ggplot(met, aes(x=dt_use)) +
  geom_line(aes(y=VWC_5, color='5cm')) +
  geom_line(aes(y=VWC_20, color='20cm')) +
  geom_line(aes(y=VWC_50, color='50cm')) +
  ggtitle('soil moisture (%)') +
  ylim(-40,100) + #add this ylime since VWC_20 is off and was replaced in May
  scale_x_datetime(labels = date_format("%b-%Y")) +
  theme_bw()

#ggplotly(sm)
sm

soiltemp <- ggplot(met, aes(x=dt_use)) +
  geom_line(aes(y=Ts_5, color='5cm')) +
  geom_line(aes(y=Ts_20, color='20cm')) +
  geom_line(aes(y=Ts_50, color='50cm')) +
  ylim(-50,50) + #add this y lim since Ts_20 went back and had high readings 
  ggtitle('soil temp (deg C)') +
  scale_x_datetime(labels = date_format("%b-%Y")) +
  theme_bw()

#ggplotly(soiltemp)
soiltemp

airtemp <- ggplot(met, aes(x= dt_use, y = Ta_C_use)) + 
  geom_point() +
  ggtitle('air temp (deg C)') +
  scale_x_datetime(labels = date_format("%b-%Y")) +
  theme_bw()

#ggplotly(airtemp)
airtemp

rh <- ggplot(met, aes(x= dt_use, y = RH_percent)) + 
  geom_point() +
  ggtitle('RH (%)') +
  scale_x_datetime(labels = date_format("%b-%Y")) +
  theme_bw()

#ggplotly(rh)
rh

swrad <- ggplot(met %>% 
                  drop_na(Rs_in),
                aes(x = dt_use)) +
  geom_line(aes(y=Rs_in, color='SW in')) +
  geom_line(aes(y=Rs_out, color='SW out')) + 
  ggtitle('shortwave rad (W/m2)') +
  scale_x_datetime(labels = date_format("%b-%Y")) +
  theme_bw()

#ggplotly(swrad)
swrad

lwrad <- ggplot(met %>% 
                  drop_na(Rl_in),
                aes(x = dt_use)) +
  geom_line(aes(y=Rl_in, color='LW in')) +
  geom_line(aes(y=Rl_out, color='LW out')) + 
  ggtitle('longwave rad (W/m2)') +
  scale_x_datetime(labels = date_format("%b-%Y")) +
  theme_bw()

#ggplotly(lwrad)
lwrad

albedo <- ggplot(met %>% 
                   drop_na(albedo),
                 aes(x= dt_use, y = albedo)) + 
  geom_point() +
  ggtitle('albedo') +
  scale_x_datetime(labels = date_format("%b-%Y")) +
  theme_bw()

#ggplotly(albedo)
albedo

rainplot <- ggplot(rain, aes(x= dt_use, y = precip_mm)) + 
  geom_point() +
  ggtitle('rain_mm') +
  scale_x_datetime(labels = date_format("%b-%Y")) +
  theme_bw()

#ggplotly(rainplot)
rainplot

stageplot <- ggplot(stage %>%
                      filter(dt_use > '2020-12-17'), # filter out data before newest install
                    aes(x= dt_use, y = stage_cm)) + 
  geom_point() +
  ggtitle('stage_update_cm') +
  scale_x_datetime(labels = date_format("%b-%Y")) +
  theme_bw()

#ggplotly(stageplot)
stageplot

```

## Rain and Stage at 15 mins

```{r rain and stage}

stage_compare <- stage %>%
  filter(dt_use > '2020-12-17')

rain_15min <- rain %>%
  slice(-c(1,2)) %>%
  group_by(dt_use = cut(dt_use, '15 min')) %>%
  summarize(precip_mm = sum(precip_mm)) %>%
  mutate(dt_use = ymd_hms(dt_use))

stage_compare <- left_join(stage_compare, rain_15min, by='dt_use')

compare <- ggplot(stage_compare %>%
                       drop_na(precip_mm) %>% 
                     filter(stage_cm > 0),
                     aes(x = dt_use)) +
  geom_line(aes(y = precip_mm/10, color = 'precip_cm')) + 
  geom_line(aes(y = stage_cm/50, color='stage_cm')) +
  scale_y_continuous(sec.axis = sec_axis(~.*50, name = "stage_cm"))

compare

```

```{r add salt slug data in}
q_obs <- read_csv(here('raw_data', 'bighorn_discharge.csv')) %>%
  mutate(dt_use = mdy_hm(datetime)) %>%
  filter(dt_use >= ymd_hms('2020-12-19 00:00:00')) %>%
  mutate(dt_use = round_date(dt_use, "15 minutes")) %>%
  select(-c(datetime, type, comments))

#join the stage and q obs
q_stage <- full_join(stage, q_obs, by="dt_use") %>%
  mutate(., stage_corr_cm = stage_cm - 1) %>%
  mutate(., stage_corr_cm = if_else(dt_use > ymd_hms('2021-05-07 12:00:00'),
                         stage_corr_cm + 3, stage_corr_cm))

#rating curve
stage_compare_plot <- ggplot(q_stage, aes(x=dt_use)) +
  geom_line(aes(y=stage_corr_cm)) +
  geom_point(aes(y=manual_stage_cm), color='red')

ggplotly(stage_compare_plot)

q_stage <- mutate(q_stage, q_Ls = (-1.461798 + 0.1875414 * stage_corr_cm)^2)

#plot discharge
q_plot = ggplot(q_stage, aes(x=dt_use)) +
  geom_line(aes(y=q_Ls)) +
  geom_point(aes(y=discharge_Ls),color='red')

ggplotly(q_plot)

#save csv in the outputs folder
write.csv(q_stage, here('outputs', 'bighorn_q.csv'))

```

